"""Data contracts between pipeline stages.

DatasetSpec (Customer Agent) -> OrchestratorPlan (Orchestrator Agent) -> EnvironmentPlan (Environment Agent)
-> SimJob (expanded in code) -> human play (game server) + AI players (simulator) -> SimResult
-> Manifest (Data Collection) -> QAMetrics (code) + QAReport (QA Agent) -> Quote (Payment Agent) -> Payment.
"""
from typing import Dict, List, Literal, Optional

from pydantic import BaseModel, Field, model_validator

from .dataset_spec import CameraSpec, DatasetSpec, Sensor, SuccessRule


# ---- Orchestrator Agent ----------------------------------------------------------------------

class PlanStep(BaseModel):
    stage: Literal["environment", "play", "simulation", "collection", "qa", "quote"]
    agent: str = Field(description="Who does it, e.g. 'Environment Agent', 'Human player', 'AI players'")
    action: str = Field(description="What they do, concretely, in MuJoCo/RoboCasa terms")
    output: str = Field(description="What this step hands to the next one")


class TaskStage(BaseModel):
    name: str
    success_check: str = Field(description="How the simulator decides this stage is done")


class DataSourcing(BaseModel):
    human_demos: int = Field(ge=0, le=50, description="Episodes a human plays in the browser game")
    ai_episodes: int = Field(ge=1, le=10000, description="Episodes generated by AI players")
    method: str = Field(description="How AI players produce episodes, e.g. demo augmentation + scripted policy")


class OrchestratorPlan(BaseModel):
    simulator: Literal["mujoco"] = "mujoco"
    framework: Literal["robocasa"] = "robocasa"
    steps: List[PlanStep] = Field(min_length=4)
    scene_build: List[str] = Field(min_length=1, description="How the scene is assembled, in order")
    task_stages: List[TaskStage] = Field(min_length=1)
    data_sourcing: DataSourcing
    data_mapping: List[str] = Field(min_length=1, description="Which recorded stream fills each requested field")
    qa_criteria: List[str] = Field(min_length=1)
    risks: List[str] = Field(default_factory=list)
    rationale: str


# ---- Environment Agent -----------------------------------------------------------------------

MAX_LAYOUT_ID = 60
MAX_STYLE_ID = 60


class EnvironmentPlan(BaseModel):
    simulator: Literal["mujoco"] = "mujoco"
    scene_template: Literal["robocasa_cafe_counter"] = "robocasa_cafe_counter"
    task: Literal["CafeServeCoffee"] = "CafeServeCoffee"
    robot: Literal["PandaOmron"] = "PandaOmron"
    layout_ids: List[int] = Field(min_length=1, description=f"Counter layouts 1..{MAX_LAYOUT_ID} to sample from")
    style_ids: List[int] = Field(min_length=1, description=f"Visual styles 1..{MAX_STYLE_ID} to sample from")
    cameras: List[CameraSpec] = Field(min_length=1)
    control_hz: int = Field(ge=10, le=30)
    max_steps: int = Field(ge=50, le=20000)
    object_instance_randomization: bool = Field(description="Sample different mug/tray models per episode")
    placement_jitter_m: float = Field(ge=0, le=0.05, description="Random xy jitter of object placements")
    base_seed: int = Field(ge=0, lt=2**31)
    focus: List[str] = Field(default_factory=list, description="What the scene should stress, in plain words")
    rationale: str

    @model_validator(mode="after")
    def _valid(self):
        for name, ids, hi in (("layout_ids", self.layout_ids, MAX_LAYOUT_ID), ("style_ids", self.style_ids, MAX_STYLE_ID)):
            bad = [i for i in ids if not 1 <= i <= hi]
            if bad:
                raise ValueError(f"{name} out of range 1..{hi}: {bad}")
            if len(set(ids)) != len(ids):
                raise ValueError(f"{name} has duplicates")
        return self


# ---- Simulation job (expanded deterministically from the plan) ----------------------------

class EpisodeParams(BaseModel):
    episode_id: str
    seed: int
    layout_id: int
    style_id: int
    placement_jitter_m: float
    player: Literal["ai", "human"] = "ai"


class SimJob(BaseModel):
    job_id: str
    order_id: str
    spec: DatasetSpec
    plan: EnvironmentPlan
    episodes: List[EpisodeParams]
    sensors: List[Sensor]
    success_rule: SuccessRule
    output_format: Literal["hdf5"] = "hdf5"


class EpisodeSummary(BaseModel):
    episode_id: str
    seed: int
    success: bool
    failure_reason: Optional[str] = None
    steps: int
    stages_completed: int


class SimResult(BaseModel):
    job_id: str
    worker: str = Field(description="Which simulator produced the data, e.g. 'mock-ai-players'")
    simulator_version: str
    dataset_path: str
    episodes: List[EpisodeSummary]
    compute_seconds: float


# ---- Human play ------------------------------------------------------------------------------

class HumanEpisode(BaseModel):
    file: str
    player_id: str
    steps: int
    stages_completed: int
    success: bool
    qa_passed: Optional[bool] = None
    qa_reasons: List[str] = Field(default_factory=list)
    replay_max_qpos_err: Optional[float] = None
    has_frames: bool = False
    reward_credits: float = 0.0
    at: Optional[float] = None


# ---- Marketplace ------------------------------------------------------------------------------

class MarketEpisode(BaseModel):
    """One episode a player submitted to a marketplace listing, with its QA verdict."""
    episode_id: str
    file: str
    player_id: str
    submitted_at: float
    steps: int
    duration_s: float
    stages_completed: int
    stages_total: int
    success: bool
    qa: Literal["pending", "pass", "fail"] = "pending"
    quality: Optional[int] = None
    qa_reason: str = ""
    reward_credits: float = 0.0
    purchased: bool = False
    has_thumb: bool = False


class Purchase(BaseModel):
    at: float
    count: int
    credits: float
    episode_ids: List[str]


# ---- Data Collection ------------------------------------------------------------------------

class Manifest(BaseModel):
    order_id: str
    worker: str
    simulator_version: str
    scene_template: str
    episodes: int
    frames: int
    sensors: List[str]
    size_bytes: int
    sha256: str
    missing_sensors: List[str] = Field(default_factory=list)


# ---- QA -------------------------------------------------------------------------------------

class QACheck(BaseModel):
    name: str
    category: Literal["structure", "task", "diversity", "reproducibility"]
    status: Literal["pass", "warn", "fail"]
    detail: str


class EpisodeQA(BaseModel):
    episode_id: str
    valid: bool
    success: bool
    reasons: List[str] = Field(default_factory=list)


class CoverageBin(BaseModel):
    lo: float
    hi: float
    count: int
    success_rate: Optional[float]


class QAMetrics(BaseModel):
    episodes_total: int
    episodes_valid: int
    success_rate: float
    failure_reasons: Dict[str, int]
    coverage: Dict[str, List[CoverageBin]]
    duplicate_seeds: int
    repro_checked: int
    repro_matched: int
    checks: List[QACheck]
    episodes: List[EpisodeQA]


class QAReport(BaseModel):
    verdict: Literal["pass", "pass_with_notes", "fail"]
    headline: str
    findings: List[str] = Field(min_length=1)
    recommended_fixes: List[str] = Field(default_factory=list)
    rerun_needed: bool = False
    rerun_focus: Optional[str] = Field(None, description="What the Environment Agent should change on a rerun")


# ---- Payment --------------------------------------------------------------------------------

class LineItem(BaseModel):
    sku: str
    description: str
    quantity: float = Field(gt=0)
    unit: str
    unit_price_usd: float
    amount_usd: float


class Quote(BaseModel):
    line_items: List[LineItem] = Field(min_length=1)
    subtotal_usd: float
    total_usd: float
    currency: Literal["USD"] = "USD"
    valid_days: int = Field(ge=1, le=90)
    notes: List[str] = Field(default_factory=list)


class Payment(BaseModel):
    status: Literal["paid"]
    mode: Literal["test", "stripe_test"] = "test"
    amount_usd: float
    reference: str
    paid_at: float
